# Generated by Django 5.2 on 2025-05-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', '매매'), ('SELL', '매도')], max_length=10, verbose_name='거래 유형')),
                ('trans_date', models.DateField(verbose_name='거래 날짜')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('trans_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction_History',
            },
        ),
    ]
